# Simply run pytest inside the docker container (.devcontainer/Docker) on
# any push to any branch

name: Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:  # Allows manual triggering of the workflow


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Build Docker image
            run: docker build -t pep750-docker -f .devcontainer/Dockerfile .
          - name: Check sort order
            run: docker run -v $(pwd):/app -w /app pep750-docker /bin/bash -c "pip install -r requirements.txt && isort --check pep"
          - name: Check formatting
            run: docker run -v $(pwd):/app -w /app pep750-docker /bin/bash -c "pip install -r requirements.txt && black --check pep"
          - name: Run tests
            run: docker run -v $(pwd):/app -w /app pep750-docker /bin/bash -c "pip install -r requirements.txt && pytest"

